#!/bin/sh
# Writes src/pagelet/timezones.lg, the IANA time zone -> country table that
# ingest uses, to stdout:
#
#   scripts/gen-timezones.sh > src/pagelet/timezones.lg
#   scripts/gen-timezones.sh path/to/zone.tab path/to/tzdata.zi > ...
#
# Every zone in zone.tab names exactly one country. Links in tzdata.zi add
# the legacy names browsers still report (Asia/Calcutta, Europe/Kiev,
# US/Pacific) with their target's country. The abbreviation-style links
# (EST -> America/Panama, CET -> Europe/Brussels) are left out: their
# targets are arbitrary, so they would name the wrong country. Links to
# zones outside zone.tab (UTC, GMT, Etc/*) have no country and drop out.
set -eu

zone_tab=${1:-/usr/share/zoneinfo/zone.tab}
tzdata_zi=${2:-/usr/share/zoneinfo/tzdata.zi}

for f in "$zone_tab" "$tzdata_zi"; do
  [ -r "$f" ] || { echo "gen-timezones: cannot read $f" >&2; exit 1; }
done

version=$(sed -n 's/^# version //p' "$tzdata_zi" | head -n 1)

awk -F'\t' -v OFS='\t' '
  FNR == NR { if ($0 !~ /^#/ && NF >= 3) { country[$3] = $1; print $3, $1 }; next }
  {
    split($0, f, " ")
    if (f[1] != "L") next
    target = f[2]; name = f[3]
    if (name in country || !(target in country)) next
    if (name ~ /^(CET|MET|EET|WET|EST|MST|HST|EST5EDT|CST6CDT|MST7MDT|PST8PDT)$/) next
    print name, country[target]
  }
' "$zone_tab" "$tzdata_zi" | LC_ALL=C sort | awk -F'\t' -v version="$version" '
  BEGIN {
    print "(ns pagelet.timezones)"
    print ""
    print ";; Generated by scripts/gen-timezones.sh from tzdata " version "; do not"
    print ";; edit by hand. An IANA time zone, as a browser reports it, to the"
    print ";; ISO 3166 code of the country it belongs to."
    print ""
    printf "(def zone->country\n  {"
  }
  { printf "%s\"%s\" \"%s\"", (NR == 1 ? "" : "\n   "), $1, $2 }
  END { print "})" }
'
